ledten/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name = 'homepage'),
    path('proc_led', views.proc_led, name = 'proc_led'),
    path('kontakt', views.kontakt, name = 'kontakt'),
    path('profil/', include('profil.urls')),
    path('produkty/', include('produkty.urls')),
    path('objednavka', views.order, name = 'order'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profil/urls.py
from django.urls import path, re_path
from . import views

app_name = 'profil'

urlpatterns = [
    path('prihlaseni', views.prihlaseni, name='prihlaseni'),
    path('registrace', views.registrace, name='registrace'),
    path('odhlasit', views.odhlasit, name='odhlasit'),
    path('<slug:user>', views.profil, name='profil'),
    path('<slug:user>/objednavky', views.objednavky, name='objednavky'),
    path('<slug:user>/recenze', views.recenze, name='recenze'),
    path('<slug:user>/nastaveni', views.nastaveni, name='nastaveni'),
]

profil/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class UserExtend(models.Model):
    #username = models.OneToOneField(User, on_delete='', unique=True, blank=True, null=True)
    #slug = models.CharField(max_length=100, default='fjasdlk', blank=True, unique=True)

    username = models.CharField(max_length=150, blank=True, unique=True, null=True)


    phone = models.CharField(max_length=100, blank=True)

    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)

    street = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    PSC = models.CharField(max_length=100, blank=True)

    img = models.ImageField(default='profil-img.png')

    created = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.username

profil/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserExtend

class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserExtendRegisterForm(forms.ModelForm):
    phone = forms.CharField(max_length=100)

    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)

    street = forms.CharField(max_length=100)
    city = forms.CharField(max_length=100)
    PSC = forms.CharField(max_length=100)

    class Meta:
        model = UserExtend
        fields = ['username', 'phone', 'first_name', 'last_name', 'street', 'city', 'PSC']



class UserUpdateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email']

class UserExtendUpdateForm(forms.ModelForm):
    phone = forms.CharField(max_length=100)

    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)

    street = forms.CharField(max_length=100)
    city = forms.CharField(max_length=100)
    PSC = forms.CharField(max_length=100)

    class Meta:
        model = UserExtend
        fields = ['username', 'phone', 'first_name', 'last_name', 'street', 'city', 'PSC', 'img']

profil/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

from .models import UserExtend
from .forms import UserRegisterForm, UserExtendRegisterForm, UserUpdateForm, UserExtendUpdateForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='profil:prihlaseni')
def profil(request, user):
    context = {
        'Euser': UserExtend.objects.get(username=user),
        'user': User.objects.get(username=user)
    }

    return render(request, 'profil/profil.html', context)

@login_required(login_url='profil:prihlaseni')
def objednavky(request, user):
    context = {
        'Euser': UserExtend.objects.get(username=user),
        'user': User.objects.get(username=user)
    }

    return render(request, 'profil/objednavky.html', context)

@login_required(login_url='profil:prihlaseni')
def recenze(request, user):
    context = {
        'Euser': UserExtend.objects.get(username=user),
        'user': User.objects.get(username=user)
    }

    return render(request, 'profil/recenze.html', context)

@login_required(login_url='profil:prihlaseni')
def nastaveni(request, user):
    user = User.objects.get(username=user)
    Euser = UserExtend.objects.get(username=user)

    if request.method == 'POST':

        u_Euser = UserExtendUpdateForm(request.POST,
                                       request.FILES,
                                       instance=Euser)

        u_user  = UserUpdateForm(request.POST,
                                 instance=user)

        if u_Euser.is_valid() and u_user.is_valid():
            u_Euser.username = u_user.get('username')

            u_Euser.save()
            u_user.save()

    else:
        u_Euser = UserExtendUpdateForm(instance=Euser)
        u_user  = UserUpdateForm(instance=user)



    context = {
        'Euser': UserExtend.objects.get(username=user),
        'user': User.objects.get(username=user),
        'u_Euser': UserExtend.objects.get(username=user),
        'u_user': User.objects.get(username=user)
    }

    return render(request, 'profil/nastaveni.html', context)

@login_required(login_url='profil:prihlaseni')
def odhlasit(request):
    if request.method=='POST':
        logout(request)
        return render(request, 'homepage.html')

def prihlaseni(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            #log in user
            user = form.get_user()
            login(request, user)

            if 'next' in request.POST:
                return redirect(request.POST.get('next'))

            else:
                return redirect('profil:profil', user=user)

        else:
            messages.error(request, 'Ups heslo nebo jmeno neodpovídá.')

    else:
        form = AuthenticationForm()

    context = {
        'form': AuthenticationForm()
    }

    return render(request, 'profil/prihlaseni.html', context)

def registrace(request):
    if request.method=='POST':
        form = UserRegisterForm(request.POST)
        eForm = UserExtendRegisterForm(request.POST)

        if form.is_valid() and eForm.is_valid():
            username = form.cleaned_data.get('username')
            user = form.save()
            login(request, user)

            eForm.username = username
            obj = eForm.save(commit=False)
            obj.save()

            return redirect('homepage')

        else:
            messages.error(request, 'Ups něco se stalo. Zkontrolujete jestli jsou všechny podmínky splněny')


    context = {
        'form': UserRegisterForm(),
        'eForm': UserExtendRegisterForm(),
    }

    return render(request, 'profil/registrace.html', context)

profil/templates/profil/nastaveni.html
{% extends 'profil/profil_layout.html' %}
{% load static %}


{% block profil-container %}

  <h3>Nastavení</h3>

  <div class="setting">
    <!--<div class="setting-item setting-username">
      <p>{{ user.username }}</p>
    </div>

    <div class="setting-item setting-email">
      <p>{{ user.email }}</p>
    </div>

    <div class="setting-item setting-password">
      <p>{{ user.password }}</p>
    </div>

    <div class="setting-item setting-phone">
      <p>{{ Euser.phone }}</p>
    </div>

    <div class="setting-item setting-first_name">
      <p>{{ Euser.first_name }}</p>
    </div>

    <div class="setting-item setting-last_name">
      <p>{{ Euser.last_name }}</p>
    </div>

    <div class="setting-item setting-street">
      <p>{{ Euser.street }}</p>
    </div>

    <div class="setting-item setting-city">
      <p>{{ Euser.city }}</p>
    </div>

    <div class="setting-item setting-PSC">
      <p>{{ Euser.PSC }}</p>
    </div>

    <div class="setting-img">

    </div>-->

    <form class="form-udaje" action="{% url 'profil:registrace' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <label for="username">Uživatelké jméno:<span>*</span></label>
      <input type="text" name="username" maxlength="150" autofocus required id="id_username">

      <label for="email">Email:<span>*</span></label>
      {{ u_user.email }}
<!--
      <label for="password1">Heslo:<span>*</span></label>
      {{ u_user.password1 }}

      <label for="password2">Potvrzení hesla:<span>*</span></label>
      {{ u_user.password2 }}
-->
      <label for="phone">Telefon:<span>*</span></label>
      <input type="text" name="phone" maxlength="100" value="+420 " required id="id_phone">

      <label for="first_name">Jméno:<span>*</span></label>
      {{ u_Euser.first_name }}

      <label for="last_name">Příjmení:<span>*</span></label>
      {{ u_Euser.last_name }}

      <label for="street">Ulice:<span>*</span></label>
      {{ u_Euser.street }}

      <label for="city">Město:<span>*</span></label>
      {{ u_Euser.city }}

      <label for="PSC">PSČ:<span>*</span></label>
      {{ u_Euser.PSC }}


      {{ u_Euser.img }}

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}

      <button class="bttn-blue" type="submit" name="update">Registrovat</button>
    </form>
  </div>

{% endblock %}

profil/templates/profil/objednavky.html
{% extends 'profil/profil_layout.html' %}
{% load static %}


{% block profil-container %}
  <h3>Objednavky</h3>

  <div class="objednavky ss-container" id="profil-objednavky">
    {% for product in "x"|rjust:"2" %}
    <div class="objednavky-objekt">
      <div class="objednavky-objekt-wrapper">
        <div class="objednavky-objekt-wrapper-produkty">

          {% for product in "x"|rjust:"2" %}
            <div class="objednavky-objekt-wrapper-produkty-produkt">
              <img src="{% static 'img/e27_1.jpg' %}" alt="e27">

              <div class="objednavky-objekt-wrapper-produkty-produkt-popis">
                <p class="text">Žárovka E27 A55 5W 400LM koule teplá bílá</p>

                <div class="objednavky-objekt-wrapper-produkty-produkt-popis-cenaks">
                  <p class="text"><span>36Kč</span> / 5ks</p>
                </div>
              </div>
            </div>
          {% endfor %}

        </div>

        <div class="objednavky-objekt-wrapper-nabidka text ">
          <button class= "blue-bttn" type="button" name="upravit-obj">Upravit objednávku</button>
          <button class="red-bttn" type="button" name="zrusit-obj">Zrušit objednávku</button>
        </div>
      </div>

      <div class="objednavky-objekt-cena">
        <p>Celkem: <span>500Kč</span></p>
      </div>
    </div>
    {% endfor %}

    {% for product in "x"|rjust:"5" %}
    <div class="objednavky-objekt">
      <div class="objednavky-objekt-wrapper">
        <div class="objednavky-objekt-wrapper-produkty">

          {% for product in "x"|rjust:"2" %}
            <div class="objednavky-objekt-wrapper-produkty-produkt">
              <img src="{% static 'img/e27_1.jpg' %}" alt="e27">

              <div class="objednavky-objekt-wrapper-produkty-produkt-popis">
                <p class="text">Žárovka E27 A55 5W 400LM koule teplá bílá</p>

                <div class="objednavky-objekt-wrapper-produkty-produkt-popis-cenaks">
                  <p class="text"><span>36Kč</span> / 5ks</p>
                </div>
              </div>
            </div>
          {% endfor %}

        </div>
      </div>

      <div class="objednavky-objekt-cena">
        <p>Celkem: <span>500Kč</span></p>
      </div>
    </div>
    {% endfor %}
  </div>

{% endblock %}

profil/templates/profil/prihlaseni.html
{% extends 'base_layout.html' %}
{% load static %}


{% block content %}

  <div class="profil-billboard">
    <div class="profil-billboard-content">
      <div class="profil-billboard-content-text">
        <div class="wrapper">
          <div class="profil-billboard-content-frame profil-frame">
            <h2>Přihlášení</h2>

            <form class="form-udaje" action="{% url 'profil:prihlaseni' %}" method="post">
              {% csrf_token %}
              {{ form }}

              {% if messages %}
                {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                    <!--<a href="#">zapoměl jsem heslo</a>-->
                  </div>
                {% endfor %}
              {% endif %}


              {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
              {% endif %}

              <button class="bttn-blue" type="submit" name="prihlaseni">Přihlásit</button>
            </form>

            <div class="profil-billboard-content-frame-a">
              <a href="#">registrovat</a>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

profil/templates/profil/profil.html
{% extends 'profil/profil_layout.html' %}
{% load static %}


{% block profil-container %}

  <h3>Profil</h3>

  <div class="profil-user-content-info info">
    <ul class="text">
      <li>{{ Euser.username }}</li>
      <li>{{ Euser.street }}</li>
      <li>{{ Euser.PSC }} {{ Euser.city }}</li>
    </ul>

    <ul class="text">
      <li><span>Tel:</span> {{ Euser.phone }}</li>
      <li><span>e-mail:</span> {{ user.email }} </li>
    </ul>
  </div>

  <div class="profil-container">
    <div class="objednavky ss-container">
      {% for product in "x"|rjust:"5" %}
      <div class="objednavky-objekt">
        <div class="objednavky-objekt-wrapper">
          <div class="objednavky-objekt-wrapper-produkty">

            {% for product in "x"|rjust:"2" %}
              <div class="objednavky-objekt-wrapper-produkty-produkt">
                <img src="{% static 'img/e27_1.jpg' %}" alt="e27">

                <div class="objednavky-objekt-wrapper-produkty-produkt-popis">
                  <p class="text">Žárovka E27 A55 5W 400LM koule teplá bílá</p>

                  <div class="objednavky-objekt-wrapper-produkty-produkt-popis-cenaks">
                    <p class="text"><span>36Kč</span> / 5ks</p>
                  </div>
                </div>
              </div>
            {% endfor %}

          </div>

          <div class="objednavky-objekt-wrapper-nabidka text ">
            <button class= "blue-bttn" type="button" name="upravit-obj">Upravit objednávku</button>
            <button class="red-bttn" type="button" name="zrusit-obj">Zrušit objednávku</button>
          </div>
        </div>

        <div class="objednavky-objekt-cena">
          <p>Celkem: <span>500Kč</span></p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

{% endblock %}

profil/templates/profil/profil_layout.html
{% extends 'base_layout.html' %}
{% load static %}


{% block content %}

  <div class="profil-billboard" id="registrace">
    <div class="profil-billboard-content" id="registrace-billboard">
      <div class="profil-billboard-content-text">
        <div class="wrapper">
          <div class="profil-user profil-frame">
            <div class="profil-user-sidenav">
              <div class="profil-user-sidenav-img">
                <img src="{{ Euser.img }}" alt="profil-img">
              </div>

              <div class="profil-user-sidenav-info">
                <h3 class="text">{{ user.username }}</h3>
              </div>

              <div class="profil-user-sidenav-list text">
                <a href="{% url 'profil:profil' user=Euser.username %}" class="profil-user-sidenav-list-item a {% if request.resolver_match.url_name == 'profil' %} profil-user-sidenav-list-item-active {% endif %}">Profil</a>
                <a href="{% url 'profil:objednavky' user=user.username %}" class="profil-user-sidenav-list-item a {% if request.resolver_match.url_name == 'objednavky' %} profil-user-sidenav-list-item-active {% endif %}">Objednávky</a>
                <a href="{% url 'profil:recenze' user=user.username %}" class="profil-user-sidenav-list-item a {% if request.resolver_match.url_name == 'recenze' %} profil-user-sidenav-list-item-active {% endif %}">Recenze</a>
                <a href="{% url 'profil:nastaveni' user=user.username %}" class="profil-user-sidenav-list-item a {% if request.resolver_match.url_name == 'nastaveni' %} profil-user-sidenav-list-item-active {% endif %}">Nastavení</a>

                <form class="logout-link" action="{% url 'profil:odhlasit' %}" method="post">
                  {% csrf_token %}
                  <button class="profil-user-sidenav-list-item profil-logout" type="submit" name="odhlasit">Odhlásit</button>
                </form>
              </div>
            </div>

            <div class="profil-user-content">
              {% block profil-container %}

              {% endblock %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

profil/templates/profil/recenze.html
{% extends 'profil/profil_layout.html' %}
{% load static %}


{% block profil-container %}

  <h3>Recenze</h3>

  <div class="profil-recenze">
    <div class="profil-recenze-container ss-container">
      {% for product in "x"|rjust:"7" %}
      <div class="product_detail-coments-container-coment">
        <div class="product_detail-coments-container-coment-user">
          <img src="{{ Euser.img.url }}" alt="profil-img">
          <h4 class="text">Alena</h4>
          <span>6.6.2018</span>
        </div>

        <div class="product_detail-coments-container-coment-text">
          <span>X X X X X</span>
          <p>Toľká škoda finále, ktoré si mal Quentin nechať dlhšie zrieť v palici! Vsuvka s odvozom je vo filme zbytočná a spomaľuje ho vo chvíli, kedy má taimingovo explodovať a všetko perfektne uzavrieť. Nebyť tohto prešľapu, ktorý mi pri Quentinovom scenáristickom majstrovstve príde nepochopiteľný, šlo by o najlepšiu Tarantinovku od Pulp Fiction. Spomalený záber na nohy bežiaceho koňa, ku-klux scéna, interakcia ústrednej dvojky s DiCapriom a vypätosť ich scén, vrcholiacich príjazdom k Samuelovi za tónov Goldsmithovej “Nicaragui”, to všetko sú už teraz legendárne filmové highlighty (príjazd k Samuelovi je pre mňa filmovou scénou roku - zakaždým 100% husina). Samuelova opičia kreácia možno trochu prehrávaná, ale správne ikonická a nezabudnuteľná. Waltz a DiCaprio úžasní, Foxx postačujúcí. Soundtrack božský. Ojedinelý westernový pulp s jednou vadou na kráse, ktorú šlo ľahko opraviť.</p>
        </div>

      </div>
      {% endfor %}
    </div>
  </div>



{% endblock %}

profil/templates/profil/registrace.html
{% extends 'base_layout.html' %}
{% load static %}


{% block content %}

  <div class="profil-billboard" id="registrace">
    <div class="profil-billboard-content" id="registrace-billboard">
      <div class="profil-billboard-content-text">
        <div class="wrapper">
          <div class="profil-billboard-content-frame profil-frame">
            <h2>Registrace</h2>

            <form class="form-udaje" action="{% url 'profil:registrace' %}" method="post">
              {% csrf_token %}

              <h3>Základní údaje</h3>

              <label for="username">Uživatelké jméno:<span>*</span></label>
              <input type="text" name="username" maxlength="150" autofocus required id="id_username">

              <label for="email">Email:<span>*</span></label>
              {{ form.email }}

              <label for="password1">Heslo:<span>*</span></label>
              {{ form.password1 }}

              <label for="password2">Potvrzení hesla:<span>*</span></label>
              {{ form.password2 }}


              <label for="phone">Telefon:<span>*</span></label>
              <input type="text" name="phone" maxlength="100" value="+420 " required id="id_phone">


              <h3>Fakturační údaje</h3>

              <label for="first_name">Jméno:<span>*</span></label>
              {{ eForm.first_name }}

              <label for="last_name">Příjmení:<span>*</span></label>
              {{ eForm.last_name }}

              <label for="street">Ulice:<span>*</span></label>
              {{ eForm.street }}

              <label for="city">Město:<span>*</span></label>
              {{ eForm.city }}

              <label for="PSC">PSČ:<span>*</span></label>
              {{ eForm.PSC }}

              <!--
              <h3>Základní údaje</h3>

              <label for="email">Email:<span>*</span></label>
              <input type="text" name="email">

              <label for="jmeno">Jméno přijmení (název firmy):</label>
              <input type="text" name="jmeno">

              <label for="PASSWORD">Heslo:<span>*</span></label>
              <input type="password" name="PASSWORD">

              <label for="PASSWORD_certificate">Potvrzení hesla:<span>*</span></label>
              <input type="password" name="PASSWORD_certificate">

              <label for="telefon">Telefon:<span>*</span></label>
              <input type="text" name="telefon" value="+420 ">

              <h3>Fakturační údaje</h3>

              <label for="ulice">Ulice:</label>
              <input type="text" name="ulice">

              <label for="mesto">Město:</label>
              <input type="text" name="mesto">

              <label for="psc">PSČ:</label>
              <input type="text" name="psc">
              -->

              {% if messages %}
                {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}

              <button class="bttn-blue" type="submit" name="registrace">Registrovat</button>
            </form>

            <div class="profil-billboard-content-frame-a">
              <a href="#">Přihlášení</a>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}