ledten/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name = 'homepage'),
    path('proc_led', views.proc_led, name = 'proc_led'),
    path('kontakt', views.kontakt, name = 'kontakt'),
    path('profil/', include('profil.urls')),
    path('produkty/', include('produkty.urls')),
    path('objednavka', views.order, name = 'order'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produkty/urls.py
from django.urls import path, re_path
from . import views

app_name = 'produkty'

urlpatterns = [
    path('', views.produkty, name='produkty'),
    path('<slug:code>', views.produkt_detail, name='detail'),
    #path('<slug:category>', views.produkty_f, name='produkty_f'),
]

profil/urls.py
from django.urls import path, re_path
from . import views

app_name = 'profil'

urlpatterns = [
    path('prihlaseni', views.prihlaseni, name='prihlaseni'),
    path('registrace', views.registrace, name='registrace'),
    path('odhlasit', views.odhlasit, name='odhlasit'),
    path('<slug:user>', views.profil, name='profil'),
    path('<slug:user>/objednavky', views.objednavky, name='objednavky'),
    path('<slug:user>/recenze', views.recenze, name='recenze'),
    path('<slug:user>/nastaveni', views.nastaveni, name='nastaveni'),
]

templates/base_layout.html
{% load static %}

<!doctype html>
<html lang="cs">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'flickity.min.css' %}">
    <link rel="stylesheet" href="{% static 'simple-scrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'baguetteBox.min.css' %}">
    <title>LedTen</title>
  </head>
  <body>
    <!--<a class="up none" href="#header">
      <i class="icono-arrow2-up"></i>
    </a>-->

      <header class="header"><!--
        <div class="top-contact text">


          <div class="top-account">
            <a href="#">Přihlásit</a> / <a href="#">Registrovat</a>
          </div>
        </div>-->

          <nav class="nvbr">
            <a class="nvbr-brand" href="{% url 'homepage' %}" name="header"><h1></h1></a>

            <div class="search">
              <!--<div class="top-contact text">
                <div class="mail-adress">
                  <a href="#">smolda.2@seznam.cz</a>
                </div>

                <div class="phone">
                  <a href="#">731 346 765</a>
                </div>
              </div>-->

                <div class="search-container">
                  <form action="{% url 'produkty:produkty' %}" method="get">
                    <input class="text" type="text" value="10W" name="jmeno__icontains" id="id_jmeno__icontain" placeholder="Hledat.." name="search">
                  </form>
                </div>



            </div>

            <div class="nvbr-right">


              <ul class="nvbr-list text">

                <li class="nvbr-list-item {% if request.resolver_match.url_name == 'homepage' %} nvbr-list-item-active {% endif %}"><h2> <a href="{% url 'homepage' %} "> Domů </a> </h2></li>
                <li class="nvbr-list-item {% if request.resolver_match.url_name == 'produkty' %} nvbr-list-item-active {% endif %}"><h2> <a href="{% url 'produkty:produkty' %} "> Produkty </a> </h2></li>
                <li class="nvbr-list-item {% if request.resolver_match.url_name == 'proc_led' %} nvbr-list-item-active {% endif %}"><h2> <a href="{% url 'proc_led' %} "> Proč LED </a> </h2></li>
                <li class="nvbr-list-item {% if request.resolver_match.url_name == 'prihlaseni' %} nvbr-list-item-active {% endif %}"><h2> <a href="{% url 'profil:prihlaseni' %} "> Přihlasit </a> </h2></li>
                <li class="nvbr-list-item {% if request.resolver_match.url_name == 'kontakt' %} nvbr-list-item-active {% endif %}"><h2> <a href="{% url 'kontakt' %} "> Kontakt </a> </h2></li>

              </ul>

              <a class="nvbr-cart" href="#">
                <div class="nvbr-cart-img">
                </div>
              </a>
            </div>


          </nav>
      </header>


      <div class="section-wrapper">
        {% block content %}

        {% endblock %}
      </div>


      <footer class="footer">
        <div class="wrapper">
          <div class="footer-top row">
            <div class="footer-top-left col-sm">

              <ul class="footer-list">
                <li class="footer-list-item"><h2> <a class="a" href="#"> Domů </a> </h2></li>
                <li class="footer-list-item"><h2> <a class="a" href="#"> Produkty </a> </h2></li>
                <li class="footer-list-item"><h2> <a class="a" href="#"> Proč LED </a> </h2></li>
                <li class="footer-list-item"><h2> <a class="a" href="#"> Jak nakupovat </a> </h2></li>
                <li class="footer-list-item"><h2> <a class="a" href="#"> Profil </a> </h2></li>
                <li class="footer-list-item"><h2> <a class="a" href="#"> Kontakt </a> </h2></li>
              </ul>

            </div>

            <div class="footer-top-right col-sm">

              <ul class="footer-list">
                <li class="footer-list-item"><h2> <a class="a" href="#"> Domů </a> </h2></li>
                <li class="footer-list-item"><h2> <a class="a" href="#"> Produkty </a> </h2></li>
                <li class="footer-list-item"><h2> <a class="a" href="#"> Proč LED </a> </h2></li>
                <li class="footer-list-item"><h2> <a class="a" href="#"> Jak nakupovat </a> </h2></li>
                <li class="footer-list-item"><h2> <a class="a" href="#"> Profil </a> </h2></li>
                <li class="footer-list-item"><h2> <a class="a" href="#"> Kontakt </a> </h2></li>
              </ul>

            </div>
          </div>

          <div class="footer-bottom">
            <p>Copyright © 2007-2018 LENAL LLС. All Rights Reserved.</p>
          </div>
        </div>
      </footer>

      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="{% static 'jquery.min.js' %}" type="text/javascript"></script>
      <script src="{% static 'popper.min.js' %}" type="text/javascript"></script>
      <script src="{% static 'bootstrap.min.js' %}" type="text/javascript"></script>

      <script src="{% static 'flickity.min.js' %}" type="text/javascript"></script>
      <script src="{% static 'echarts.min.js' %}" type="text/javascript"></script>
      <script src="{% static 'echarts.js' %}" type="text/javascript"></script>
      <script src="{% static 'flickity.js' %}" type="text/javascript"></script>
      <script src="{% static 'calculator.js' %}" type="text/javascript"></script>
      <script src="{% static 'calc.js' %}" type="text/javascript"></script>

      <script src="{% static 'baguetteBox.min.js' %}" type="text/javascript"></script>

      <script src="{% static 'simple-scrollbar.min.js' %}" type="text/javascript"></script>
      <script src="{% static 'scripts.js' %}" type="text/javascript"></script>
      <script src="{% static 'counter-input.js' %}" type="text/javascript"></script>

   </body>
</html>

templates/calculator.html
{% load static %}

{% block calculator %}
  <section class="calculator">
  <div class="wrapper">
    <h4 class="h4 text">Kalkulačka</h4>

    <div class="calculator-container">
      <div class="calculator-container-set">

        <div class="range-slider">
          <label class="range-slider__label text">Výkon současných klascikých žárovek</label>
          <input class="range-slider__range" type="range" value="60" min="0" max="500">
          <span class="range-slider__value" id="range-slider__value2">0</span>
        </div>

        <div class="range-slider">
          <label class="range-slider__label text">Výkon nových LED žárovek</label>
          <input class="range-slider__range" type="range" value="10" min="0" max="500">
          <span class="range-slider__value" id="range-slider__value3">0</span>
        </div>

        <div class="range-slider">
          <label class="range-slider__label text">Cena LED žárovky</label>
          <input class="range-slider__range" type="range" value="39" min="0" max="200">
          <span class="range-slider__value" id="range-slider__value4">0</span>
        </div>

        <div class="range-slider">
          <label class="range-slider__label text">Cena za kWh</label>
          <input class="range-slider__range" type="range" value="4" min="0" max="50">
          <span class="range-slider__value" id="range-slider__value1">0</span>
        </div>

        <div class="range-slider">
          <label class="range-slider__label text">Počet žárovek</label>
          <input class="range-slider__range" type="range" value="10" min="0" max="300">
          <span class="range-slider__value" id="range-slider__value5">0</span>
        </div>

        <div class="range-slider">
          <label class="range-slider__label text">Průměrná denní doba svícení</label>
          <input class="range-slider__range" type="range" value="6" min="0" max="24">
          <span class="range-slider__value" id="range-slider__value6">0</span>
        </div>
      </div>

      <div class="calculator-container-graph why-led-graph ct-golden-section">
        <div id="calculator-container-graph-graph" style="width: 100%; height:420px;"></div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/echarts.html
{% load static %}



{% block echarts %}

  <script src="{% static 'echarts.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'echarts.js' %}" type="text/javascript"></script>
  <script src="{% static 'calc.js' %}" type="text/javascript"></script>
{% endblock %}

templates/homepage.html
{% extends 'base_layout.html' %}
{% load static %}


  {% block content %}


      <div class="header-billboard" id="billboard-static">
        <div class="header-billboard-content">
          <div class="header-billboard-content-text">
            <div class="wrapper">
              <div class="header-billboard-content-text-wrapper">
                <img src="{% static 'img/ledten_light.png' %}" alt="ledten">

                <p>Duis aute irur dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

                <a class="bttn a text" href="#">Nabídka produktů</a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="header-billboard-space">

      </div>

      {% block why1 %}{% include 'why1.html' %}{% endblock %}

      {% block calculator %}{% include 'calculator.html' %}{% endblock %}

      {% block product-carousel %}{% include 'product-carousel.html' %}{% endblock %}

      <section class="zasilat">
        <div class="wrapper">
          <div class="zasilat-container">
            <h4 class="h4 text">Posílat novinky</h4>
            <p class="text">Nechte si posílat novinky, ať vám nic neujde.</p>

            <form class="zasilat-container-form" action="index.html" method="post">
              <input class="text" type="text" name="zasilat" placeholder="zde vložte svůj email">
              <button class="text" type="button" name="button">Odeslat</button>
            </form>
          </div>
        </div>
      </section>

  {% endblock %}

templates/kontakt.html
{% extends 'base_layout.html' %}
{% load static %}


{% block content %}

  <div class="kontakt-billboard">
    <iframe width="100%" frameborder="0" style="border:0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2570.3252569583688!2d18.235331158381285!3d49.892696621772515!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4713e20ebef5ed93%3A0x11f5ba1ea2a38b04!2sMarkvartovick%C3%A1+68%2F54%2C+747+14+Ludge%C5%99ovice!5e0!3m2!1scs!2scz!4v1546706273804"></iframe>

    <div class="kontakt-billboard-content visible">
      <div class="kontakt-billboard-content-container">
        <h3 class="h4 text">kontakty</h3>

        <div class="info">
          <ul class="text">
            <li>Jana Sládková - LedTen.cz</li>
            <li>Markvartovická 68/54</li>
            <li>747 14 Ludgeřovice</li>
            <li><span>IČ:</span> 73076953</li>
            <li><span>DIČ:</span> CZ7152025551</li>
          </ul>

          <ul class="text">
            <li><span>Tel:</span> <a href="tel:604243347" class="a ab">604 243 347</a></li>
            <li><span>Tel:</span> <a href="tel:605089367" class="a ab">605 089 367</a></li>
            <li><span>e-mail:</span> <a href="mailto:ledteninfo@gmail.com">ledteninfo@gmail.com</a></li>
          </ul>
        </div>

      </div>
    </div>
    <button class="mapa bttn a text">Ukázat mapu</button>

  </div>

{% endblock %}

templates/less.html
{% load static %}

{% block less %}

  <section class="why" style=" background: #f6f6f6;">
    <div class="wrapper">
      <div class="why-content">
        <div class="why-container" style="margin-top: 20px;">
            <h4 class="h4 text">Menší světelná spotřeba</h4>
            <p>LED diody mají lepší kvalitu rozložení světla a zaměřují světlo v jednom směru, na rozdíl od jiných typů osvětlení, které způsobují ztrátu energie tím, že vydávají světlo ve všech směrech, často osvětlující oblasti, kde se světlo nevyžaduje (například strop). To znamená, že pro dosažení stejné úrovně jasu, kterou vypouští fluorescenční a žárovkové světlo, je zapotřebí méně LED. Méně osvětlení sníží spotřebu energie a bude proto přínosem pro životní prostředí.</p>
        </div>

        <img src="{% static 'img/less.png' %}" alt="LED žárovka">
      </div>

    </div>
  </section>

{% endblock %}

templates/life.html
{% load static %}

{% block life %}

  <section class="why" style=" background: #f6f6f6;">
    <div class="wrapper">
      <div class="why-content">
        <div class="why-container">
            <h4 class="h4 text">Životnost</h4>
            <p>
              Delší životnost znamená nižší emise uhlíku. Kontrolky LED svítí až šestkrát déle než jiné typy světel, což snižuje potřebu častých výměn. Výsledkem je použití méně světla, a proto je potřeba méně zdrojů pro výrobní procesy, obalové materiály a dopravu.
            </p>
        </div>
        <img style="height: 200px;" src="{% static 'img/time.png' %}" alt="LED žárovka">
      </div>

    </div>
  </section>

{% endblock %}

templates/order.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
  <section class="orders">
    <div class="wrapper">
      <div class="orders-items">
        <h3 class="h4 text">Objednávka</h3>

        {% for x in "y"|rjust:"5" %}
          <div class="orders-items-item ">
            <div class="text orders-items-item-jmeno">
              <img src="{% static 'img/e27_1.jpg' %}" alt="e27">
              <h4>Žárovka E27 A55 5W 400LM koule teplá bílá</h4>
            </div>
            <form class="orders-items-item-ks" action="" method="post">
              39Kč/ks
              <div class="orders-items-item-ks-content">
                <input type='button' value='' class='minus' />
                <input type='number' min="0" size='10' class='value-number' value='1' />
                <input type='button' value='' class='plus' />
              </div>
            </form>

            <div class="orders-items-item-skladem">
              <p>Skladem</p>
            </div>

            <div class="orders-items-item-cena">
              <p class="orders-items-item-cena-celkem">390Kč</p>
            </div>

            <form class="orders-items-item-x" action="index.html" method="post">
              <input type="button" name="x">
            </form>

          </div>
        {% endfor %}

        <div class="celkova_cena">
          <h4 class="text">Celkem: <span>1950Kč</span></h4>
        </div>
      </div>
    </div>
  </section>

  <section class="order_shipping_paymant">
    <div class="wrapper">

      <div class="order_shipping_paymant-container">
        <div class="order_shipping_paymant-container-shipping">
          <h3 class="h4 text">Doprava</h3>

          <form class="" action="index.html" method="post">
            <label for="balik-na-postu" class="order-radio">
              <div class="radio">
                <input id="balik-na-postu" name="radio" type="radio" checked>
                <label for="balik-na-postu" class="radio-label"><img src="{% static 'img/ceska-posta-balik-na-postu.png' %}" alt="balik na poštu"> ČESKÁ POŠTA - balík na poštu </label>
              </div>

              <label class="cena-blue">120Kč</label>
            </label>

            <label for="balik-do-ruky" class="order-radio">
              <div class="radio">
                <input id="balik-do-ruky" name="radio" type="radio" checked>
                <label for="balik-do-ruky" class="radio-label"><img src="{% static 'img/ceska-posta-balik-do-ruky.png' %}" alt="balik do ruky"> ČESKÁ POŠTA - balík do ruky </label>
              </div>

              <label class="cena-blue">140Kč</label>
            </label>

            <label for="PPL" class="order-radio">
              <div class="radio">
                <input id="PPL" name="radio" type="radio" checked>
                <label for="PPL" class="radio-label"><img src="{% static 'img/ppl.jpeg' %}" alt="PPL"> PPL </label>
              </div>

              <label class="cena-blue">99Kč</label>
            </label>

            <label for="PPL-dobirka" class="order-radio">
              <div class="radio">
                <input id="PPL-dobirka" name="radio" type="radio" checked>
                <label for="PPL-dobirka" class="radio-label"><img src="{% static 'img/ppl.jpeg' %}" alt="PPL-dobírka">  PPL - dobírka </label>
              </div>

              <label class="cena-blue">120Kč</label>
            </label>

            <label for="osoni-odber" class="order-radio">
              <div class="radio">
                <input id="osoni-odber" name="radio" type="radio" checked>
                <label for="osoni-odber" class="radio-label"><img src="{% static 'img/osobni-odber.png' %}" alt="osobní odběr">  Osobní odběr </label>
              </div>

              <label class="cena-blue"><span class="Zdarma1">Zdarma</span></label>
            </label>


            <label for="balik-na-postu-obalka" class="order-radio">
              <div class="radio">
                <input id="balik-na-postu-obalka" name="radio" type="radio" checked>
                <label for="balik-na-postu-obalka" class="radio-label"><img src="{% static 'img/ceska-posta-balik-na-postu.png' %}" alt="balik na poštu obálka"> ČESKÁ POŠTA - balík na poštu obálka</label>
              </div>

              <label class="cena-blue">100Kč</label>
            </label>

            <label for="balik-do-ruky-obalka" class="order-radio">
              <div class="radio">
                <input id="balik-do-ruky-obalka" name="radio" type="radio" checked>
                <label for="balik-do-ruky-obalka" class="radio-label"><img src="{% static 'img/ceska-posta-balik-do-ruky.png' %}" alt="balik do ruky obálka"> ČESKÁ POŠTA - balík do ruky obálka</label>
              </div>

              <label class="cena-blue">70Kč</label>
            </label>

            <!--<div class="radio">
              <input id="radio-3" name="radio" type="radio" disabled>
              <label for="radio-3" class="radio-label">Disabled</label>
            </div>-->
          </form>
        </div>

        <div class="order_shipping_paymant-container-paymant">
          <h3 class="h4 text">Platba</h3>

          <form class="" action="index.html" method="post">
            <label for="dobirkou" class="order-radio">
              <div class="radio">
                <input id="dobirkou" name="radio" type="radio" checked>
                <label for="dobirkou" class="radio-label"><img src="{% static 'img/paymant-cash.png' %}" alt="Dobírkou"> Dobírkou</label>
              </div>

              <label><span class="Zdarma1">Zdarma</span></label>
            </label>

            <label for="prevodem" class="order-radio">
              <div class="radio">
                <input id="prevodem" name="radio" type="radio" checked>
                <label for="prevodem" class="radio-label"><img src="{% static 'img/paymant-transfer2.png' %}" alt="Převodem"> Převodem</label>
              </div>

              <label><span class="Zdarma1">Zdarma</span></label>
            </label>

            <!--<div class="radio">
              <input id="radio-3" name="radio" type="radio" disabled>
              <label for="radio-3" class="radio-label">Disabled</label>
            </div>-->
          </form>
        </div>
      </div>

      <div class="celkova_cena">
        <h4 class="text">Celkem: <span>140Kč</span></h4>
      </div>
    </div>
  </section>

  <section class="order_info">
    <div class="wrapper">
      <h3 class="h4 text">Dodací údaje</h3>

      <div class="order_info-container">
        <div class="order_info-container-left">
          <h4 class="h44">Osobní údaje</h4>

          <form class="form-udaje" action="index.html" method="post">

            <label for="email">Email:<span>*</span></label>
            <input type="text" name="email">

            <label for="telefon">Telefon:<span>*</span></label>
            <input type="text" name="telefon" value="+420 ">

            <label for="jmeno">Jméno přijmení (název firmy):<span>*</span></label>
            <input type="text" name="jmeno">

            <label for="ulice">Ulice:<span>*</span></label>
            <input type="text" name="ulice">

            <label for="mesto">Město:<span>*</span></label>
            <input type="text" name="mesto">

            <label for="psc">PSČ:<span>*</span></label>
            <input type="text" name="psc">
          </form>
        </div>

        <div class="order_info-container-left">
          <h4 class="h44">Dodací adresa</h4>

          <form class="form-udaje" action="index.html" method="post">

            <label for="jmeno">Jméno přijmení (název firmy):</label>
            <input type="text" name="jmeno">

            <label for="ulice">Ulice:</label>
            <input type="text" name="ulice">

            <label for="mesto">Město:</label>
            <input type="text" name="mesto">

            <label for="psc">PSČ:</label>
            <input type="text" name="psc">
          </form>
        </div>
      </div>

      <div class="text order_info-bottom">
        <form action="index.html" method="post">
          <div class="celkova_cena">
            <h4 class="text">1950Kč + 140Kč = <span>2090Kč</span></h4>
          </div>

          <button class="bttnb" type="button" name="button">Odeslat objednávku</button>
        </form>

        <a href="#">Chci ještě vybírat</a>
      </div>
    </div>
  </section>
{% endblock %}

templates/patice.html
{% load static %}

{% block patice %}
  <section class="patice">
    <div class="wrapper">
      <h4 class="h4 text">Patice</h4>

      <div class="patice-img">
        <img src="{% static 'img/patice.jpg' %}" alt="patice">
      </div>
    </div>
  </section>
{% endblock %}

templates/proc_led.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}

  <div class="header-billboard">
    <div class="header-billboard-content">
      <div class="header-billboard-content-text">
        <div class="wrapper">
          <div class="header-billboard-content-text-wrapper">
          </div>
        </div>
      </div>
    </div>
  </div>

  {% block why1 %}{% include 'why1.html' %}{% endblock %}

  {% block life %}{% include 'life.html' %}{% endblock %}

  {% block toxicity %}{% include 'toxicity.html' %}{% endblock %}

  {% block less %}{% include 'less.html' %}{% endblock %}

  {% block patice %}{% include 'patice.html' %}{% endblock %}

  {% block calculator %}{% include 'calculator.html' %}{% endblock %}

  {% block product-carousel %}{% include 'product-carousel.html' %}{% endblock %}

  <style media="screen">
    .why1 a{
      display: none;
    }
  </style>
{% endblock %}

templates/product-carousel.html
{% load static %}

{% block product-carousel %}

  <section class="products-carousel">
    <div class="wrapper">
      <h4 class="h4 text">Produkty</h4>

      <div class="products-carousel-container">

        {% for prod in products %}
          {% for productImg in productsImg %}
            {% if productImg.code == prod.code %}
              <div class="carousel-cell">
                {% include 'product.html' with product=prod productImg=productImg %}
              </div>
            {% endif %}
          {% endfor %}
        {% endfor %}
      </div>

      <div class="products-carousel-link">
        <a class="bttnb a" href="#">Nabídka produktů</a>
      </div>
    </div>
  </section>

{% endblock %}

templates/product.html
{% load static %}

{% block product %}

  <div class="product-card">
    <a class="product-card-wrapper a" href="/produkty/{{ product.code }}">
      <div class="product-card-wrapper-img">
        <img src="{{ productImg.img.url }}" alt="{{ product.name }}">
      </div>

      <h5 class="text">{{ product.card }}</h5>

      <h6 class="text">{{ product.cena }}Kč</h6>
    </a>
  </div>
{% endblock %}

templates/toxicity.html
{% load static %}

{% block toxicity %}

  <section class="why">
    <div class="wrapper">
      <div class="why-content">
        <img src="{% static 'img/recy.jpg' %}" alt="LED žárovka">

        <div class="why-container">
            <h4 class="h4 text">Žádné toxické prvky</h4>
            <p>
              LED světla neobsahují žádné toxické prvky. Většina kanceláří v současné době používá fluorescenční proužky, které obsahují škodlivé chemikálie, jako je rtuť. To bude kontaminovat životní prostředí při likvidaci odpadu v skládkách. Likvidace musí být provedena prostřednictvím registrovaného nosiče odpadu, takže přepnutí na LED zabraňuje nákladovým a časovým důsledkům požadovaným pro vyhovující zneškodnění a pomáhá chránit životní prostředí před dalším toxickým odpadem.
            </p>
        </div>
      </div>

    </div>
  </section>

{% endblock %}

templates/why1.html
{% load static %}

{% block why1 %}
  <section class="why1">
    <div class="wrapper">
      <h4 class="h4 text">Proč LED?</h4>
      <div class="why1-content">
        <div class="why1-container">
            <div class="why1-img">
              <img src="{% static 'img/ledbulb.jpg' %}" alt="LED žárovka">
              <h5 class="text">LED</h5>
            </div>
            <div class="why1-graph ct-golden-section">
              <div id="main" style="width: 100%; height:100%;"></div>

            </div>
            <div class="why1-img">
              <img src="{% static 'img/zarovka.jpg' %}" alt="žárovka">
              <h5 class="text">Klasická</h5>
            </div>
        </div>

        <p class="text">
          LED světla jsou až o 80% účinnější než tradiční osvětlení, jako jsou zářivky a žárovky. 95% energie v LED je přeměněno na světlo a pouze 5% je zbytečné jako teplo. To je ve srovnání s fluorescenčními světly, které převádějí 95% energie na teplo a pouze 5% na světlo! LED světla také čerpají mnohem méně energie než tradiční osvětlení; Typický 84 Watt fluorescenční světlo může být nahrazeno 36 W LED, aby se dosáhlo stejné úrovně světla. Snížení spotřeby energie snižuje poptávku z elektráren a snižuje emise skleníkových plynů.
        </p>

        <a href="#">Číst více</a>
      </div>

    </div>
  </section>
{% endblock %}